[package]
name = "algebra-dsl-server"
version = "0.1.0"
authors = ["Adam Dunlap <dunlapadam@gmail.com>"]

[dependencies]
websocket = "0.17.1"
iron = "0.4"
router = "0.2"
staticfile = "0.3.1"
mount = "0.2"


[dependencies.khwarizmi]
path = "../khwarizmi"
