[package]
name = "algebra-dsl-server"
version = "0.1.0"
authors = ["Adam Dunlap <dunlapadam@gmail.com>"]

[dependencies]
websocket = "0.22"
iron = "0.6"
router = "0.6"
staticfile = "0.5"
mount = "0.4"
serde_derive = "1"
serde_json = "1"
serde = "1"

[dependencies.khwarizmi]
path = "../khwarizmi"
